#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# pre-processing
runApplication blockMesh
runApplication checkMesh
runApplication setFields

if [ "$1" = "parallel" ]
then
    # run in parallel mode
    runApplication decomposePar -cellProc
    runParallel $(getApplication)
    runApplication reconstructPar
else
    # run in serial mode
    runApplication $(getApplication)
fi

#------------------------------------------------------------------------------