#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wmake $targetType icoThermoVoF

wmake $targetType icoPhaseChangeVoF

wmake $targetType icoMulticomponentVoF

wmake $targetType icoMultiPhaseChangeVoF