#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# pre-processing
runApplication blockMesh
runApplication checkMesh

# run in parallel
runApplication decomposePar -cellProc
runParallel $(getApplication)
runApplication reconstructPar

foamPostProcess -noZero -func locateInterface

. $WM_PROJECT_USER_DIR/.venv/bin/activate
NAME="comparison.pdf"
python3 compare.py $NAME
wslview $NAME
deactivate

#------------------------------------------------------------------------------