#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# pre-processing
runApplication blockMesh
runApplication checkMesh

if [ "$1" = "serial" ]
then
    # run in serial mode
    runApplication foamRun
else
    # run in parallel mode
    runApplication decomposePar -cellProc
    runParallel foamRun
    runApplication reconstructPar
fi

foamPostProcess -noZero -func locateInterface

. $WM_PROJECT_USER_DIR/.venv/bin/activate
NAME="comparison.pdf"
python3 compare.py $NAME
explorer.exe $NAME
deactivate

#------------------------------------------------------------------------------