#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wmake $targetType OpenFOAM/ErrorFunction

wmake $targetType meshTools/zoneGenerators/volume/spheres

#wmake $targetType twoPhaseModels/interfaceProperties

#wmake $targetType physicalProperties/solidificationModels

#wmake $targetType physicalProperties/evaporationModels

#fvModels/Allwmake $targetType $*

wmake $targetType functionObjects/traceSurface